"""Add DyeResult

Revision ID: 78e1b30fc11b
Revises: fc4f47be4488
Create Date: 2025-04-09 10:51:54.721378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e1b30fc11b'
down_revision = 'fc4f47be4488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dye_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dye_material_id', sa.Integer(), nullable=False),
    sa.Column('mordant_id', sa.Integer(), nullable=False),
    sa.Column('final_hex', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dye_material_id'], ['dye_materials.id'], name=op.f('fk_dye_results_dye_material_id_dye_materials')),
    sa.ForeignKeyConstraint(['mordant_id'], ['mordants.id'], name=op.f('fk_dye_results_mordant_id_mordants')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dye_results')
    # ### end Alembic commands ###
