"""Add name field to DyeResult

Revision ID: a0e642e1c306
Revises: 78e1b30fc11b
Create Date: 2025-04-13 18:52:48.365673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e642e1c306'
down_revision = '78e1b30fc11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dye_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dye_results', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
