"""Added dyes table

Revision ID: d82a0c3b080b
Revises: 
Create Date: 2025-03-31 13:40:58.324944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82a0c3b080b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dye_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_color', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mordants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dye_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dye_material_id', sa.Integer(), nullable=False),
    sa.Column('mordant_id', sa.Integer(), nullable=False),
    sa.Column('resulting_color', sa.String(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dye_material_id'], ['dye_materials.id'], name=op.f('fk_dye_results_dye_material_id_dye_materials')),
    sa.ForeignKeyConstraint(['mordant_id'], ['mordants.id'], name=op.f('fk_dye_results_mordant_id_mordants')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dye_results')
    op.drop_table('mordants')
    op.drop_table('dye_materials')
    # ### end Alembic commands ###
