"""Add Mordant

Revision ID: fc4f47be4488
Revises: 0ff831254006
Create Date: 2025-04-09 10:50:55.265450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4f47be4488'
down_revision = '0ff831254006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mordants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('r_effect', sa.Integer(), nullable=False),
    sa.Column('g_effect', sa.Integer(), nullable=False),
    sa.Column('b_effect', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mordants')
    # ### end Alembic commands ###
